name: Close PRs from non-collaborators
on:
  pull_request_target:
    types: [opened]

jobs:
  close-unauthorized:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your interest! We currently only accept PRs from invited collaborators."
        if: github.event.pull_request.author_association == 'NONE'
